
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    # env:
    #   # ROOCH_ORACLE_ADDRESS= ${{ secrets.ROOCH_ORACLE_ADDRESS }}
    #   # ROOCH_PRIVATE_KEY= ${{ secrets.ROOCH_PRIVATE_KEY }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }} üõéÔ∏è
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          persist-credentials: false

      - name: Install üîß dependencies
        run: npx yarn install

      - name: build
        run: npx yarn build

      - name: Use Node.js ${{ matrix.node-version }} üõéÔ∏è
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node-version }}
          persist-credentials: false

      - name: Install üîß dependencies
        run: npx yarn install

      - name: build
        run: npx yarn build

      # Set up Rust
      - uses: actions/setup-rust@v1
        with:
          toolchain: stable
      
      - name: Clone and setup Rooch
        run: |
          git clone https://github.com/rooch-network/rooch.git _rooch
          cd _rooch
          cargo build
          cp target/debug/rooch ~/.cargo/bin/
          cd rooch
          rooch move test
